name: Prod CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  fetest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "16.18.1"
      - name: Install frontend dependencies & test
        run: npm ci
      - name: App Coverage Test
        run: npm run test:unit -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: app-coverage-report
          path: coverage
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload Build Folder
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist
      - name: Zip App Assets
        run: |
          zip -r build.zip ./dist
          zip -r coverage.zip ./coverage
          mkdir asset_artifacts
          mv build.zip asset_artifacts
          mv coverage.zip asset_artifacts
      - name: Upload Asset Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: assets-artifacts
          path: asset_artifacts
  release:
    needs: [fetest]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.4.0"
      - name: Install root
        run: npm install
      - name: Download Asset Artifacts
        uses: actions/download-artifact@v3
        with:
          name: assets-artifacts
      - name: Create prod release
        if: github.event_name == 'push'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      